import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({headless:true}),errors=[];
const expect=(ok,message)=>{if(!ok)throw new Error(message);};
try{
 await mkdir('artifacts',{recursive:true});
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/?chapter=2&test=1',{waitUntil:'networkidle'});await page.locator('#begin').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('#begin').disabled);
 expect((await page.locator('.chapter').textContent())?.includes('CHAPTER 02'),'chapter router failed');expect((await page.locator('#population').textContent())?.trim()==='8 匹','direct fallback is not 8');await page.locator('#begin').click();
 // 座標はすべて迷路データ(chapter2Test.maze)から取る。
 const maze=await page.evaluate(()=>window.chapter2Test.maze);
 const shaft=maze.centipede,wide=maze.slits.find(s=>s.width>=1.2),narrowSlit=maze.slits.find(s=>s.width<1.2);
 expect(wide&&narrowSlit,'maze is missing a wide or a narrow slit');
 const snapshot=()=>page.evaluate(()=>window.chapter2Test.snapshot());
 await page.evaluate(c=>{window.chapter2Test.setPosition(c.x,c.yBottom-4);window.chapter2Test.setEnemy('chase',c.yTop+4,0,c.x);},shaft);
 await page.waitForFunction(y=>window.chapter2Test.snapshot().enemy.y>y+.4,shaft.yTop+4,{timeout:3000});
 expect((await snapshot()).enemy.y>shaft.yTop+4.4,'centipede did not follow player down the shaft');
 await page.evaluate(s=>window.chapter2Test.setPosition(s.x,s.y),wide);expect((await snapshot()).sheltered,'passable gap did not shelter player');
 await page.evaluate(a=>window.chapter2Test.setEnemy('chase',a.w.y+2,0,a.c.x),{w:wide,c:shaft});await page.waitForTimeout(120);
 expect((await snapshot()).enemy.state==='recover','centipede did not abandon sheltered prey');
 const lane=maze.geji;
 await page.evaluate(g=>{window.chapter2Test.setPosition(g.xRight-2,g.y);window.chapter2Test.setEnemy('chase',g.y,0,g.xRight-4);},lane);
 const passing=await snapshot();await page.waitForTimeout(70);
 expect((await snapshot()).survivors===passing.survivors,'centipede hit without head contact');
 await page.evaluate(c=>{window.chapter2Test.setPosition(c.x,c.yTop+6);window.chapter2Test.setEnemy('warning',c.yTop+10,0,c.x);},shaft);
 const before=(await snapshot()).survivors;await page.waitForTimeout(300);let state=await snapshot();
 expect(state.survivors===before&&state.enemy.state==='warning','centipede caught before 0.6s warning');
 await page.waitForFunction(group=>window.chapter2Test.snapshot().survivors===group-1,before,{timeout:5000});
 expect((await snapshot()).survivors===before-1,'centipede contact did not remove exactly one survivor');
 await page.evaluate(l=>{window.chapter2Test.setPosition(l.x,l.y);window.chapter2Test.setEnemy('patrol',l.y-30,0,l.x);},maze.lair);
 const geckoBefore=(await snapshot()).survivors;
 await page.waitForFunction(()=>window.chapter2Test.snapshot().geckoWarning>0,null,{timeout:5000});
 expect((await snapshot()).geckoWarning>0,'gecko warning did not precede its strike');
 await page.waitForFunction(n=>window.chapter2Test.snapshot().survivors===n-1,geckoBefore,{timeout:5000});
 await page.evaluate(m=>{window.chapter2Test.setPosition(m.x,m.y);window.chapter2Test.startMolt();},maze.molt);
 await page.waitForFunction(()=>window.chapter2Test.snapshot().molted,null,{timeout:12000});
 const postMolt=await snapshot();expect(postMolt.molted&&postMolt.bodySize===1.2,'chapter molt did not grow and persist the body: '+JSON.stringify(postMolt));
 // 4齢(1.20)が 1.10 の隙間へ押し込むと通れない。
 await page.evaluate(s=>window.chapter2Test.setPosition(s.axis==='v'?s.x:s.x-2,s.axis==='v'?s.y-2:s.y),narrowSlit);
 await page.keyboard.down(narrowSlit.axis==='v'?'ArrowDown':'ArrowRight');
 await page.waitForFunction(()=>/通れない/.test(document.querySelector('#warning').textContent||''),null,{timeout:4000});
 expect(/通れない/.test((await page.locator('#warning').textContent())||''),'narrow gap feedback missing');
 await page.keyboard.up(narrowSlit.axis==='v'?'ArrowDown':'ArrowRight');
 await page.evaluate(g=>window.chapter2Test.setPosition(g.x,g.y),maze.goal);
 await page.waitForFunction(()=>window.chapter2Test.snapshot().humanTimer>=1.2,null,{timeout:4000});
 expect(/床板|重い影/.test((await page.locator('#warning').textContent())||''),'human warning did not precede ending');
 await page.waitForFunction(()=>!document.querySelector('#ending').hidden,null,{timeout:5000});
 await page.screenshot({path:'artifacts/chapter2-three-shaft.png'});await page.close();
 const carried=await browser.newPage({viewport:{width:1280,height:800}});carried.on('pageerror',e=>errors.push(e.message));await carried.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'});await carried.evaluate(()=>localStorage.setItem('g-survival-progress-v1',JSON.stringify({version:1,unlockedChapter:2,currentChapter:2,survivors:13,instar:3,bodySize:1.02,injuries:[]})));await carried.goto('http://127.0.0.1:5173/?chapter=2&from=chapter1',{waitUntil:'networkidle'});await carried.waitForFunction(()=>!document.querySelector('#begin').disabled);expect((await carried.locator('#population').textContent())?.trim()==='13 匹','survivor carry-over failed');expect(errors.length===0,'page errors: '+errors.join(' | '));
 console.log('chapter2 audit PASS: maze-driven coordinates, router, 8/13 survivors, gap shelter, narrow rejection after molt, centipede warning/chase/head-only contact/recover, gecko warning, molt 1.2, wall-hole ending, page errors=0');
}finally{await browser.close();}
