import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const url=process.env.GECKO_AUDIT_URL??'http://127.0.0.1:5173',b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:1200,height:800}}),errors=[];
p.on('pageerror',e=>errors.push(e.message));await p.route('**/gecko-audit-preview',r=>r.fulfill({contentType:'text/html',body:'<body style="margin:0"></body>'}));await p.goto(url+'/gecko-audit-preview');
const auditScale=Number(process.env.GECKO_AUDIT_SCALE??.4);
const results=await p.evaluate(async scale=>{
 const T=await import('/node_modules/three/build/three.module.js'),G=await import('/src/gecko.ts');await G.loadGecko();const g=G.createGecko(scale),other=G.createGecko(scale),scene=new T.Scene();scene.background=new T.Color('#4a4b46');scene.add(g);scene.add(new T.HemisphereLight('#fff5df','#727978',2));const light=new T.DirectionalLight(0xffffff,2.5);light.position.set(3,-2,6);scene.add(light);
 const wall=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:'#888b83',roughness:1}));wall.position.z=-.01;scene.add(wall);const cam=new T.PerspectiveCamera(38,1200/800,.1,100),renderer=new T.WebGLRenderer({antialias:true});renderer.setSize(1200,800);renderer.setPixelRatio(1);renderer.toneMapping=T.ACESFilmicToneMapping;document.body.append(renderer.domElement);
 const draw=(x=0,y=0)=>{cam.position.set(x+1,y-4,5.5);cam.lookAt(x-1.25,y,0);renderer.render(scene,cam);};
 const pose={x:0,y:0,z:0,heading:0,mode:'idle'};G.animateGecko(g,0,pose);G.animateGecko(other,0,{...pose,x:10});let meshes=[];g.traverse(o=>{if(o.isSkinnedMesh)meshes.push(o);});const skin=meshes[0],otherSkin=other.getObjectByName(skin.name);const beforeOther=other.getObjectByName('fore_L_lower').matrixWorld.clone(),initial=G.geckoDebug(g);let stableError=0,maxStanceError=0,steps=0,curl=0,lift=0,finite=true,previous=initial;
 for(let i=1;i<=120;i++){G.animateGecko(g,i/60,pose);const d=G.geckoDebug(g);for(let n=0;n<4;n++)stableError=Math.max(stableError,new T.Vector3().fromArray(d.feet[n].ankle).distanceTo(new T.Vector3().fromArray(initial.feet[n].ankle)));}
 const idle=G.geckoDebug(g);draw();window.__geckoReview={g,G,T,scene,cam,renderer,draw,pose};
 for(let i=1;i<=240;i++){const x=i*.012,y=.45*Math.sin(i/90);G.animateGecko(g,2+i/60,{...pose,x,y,mode:'return'});const d=G.geckoDebug(g);for(let n=0;n<4;n++){const f=d.feet[n];if(!f.stance&&previous.feet[n].stance)steps++;if(f.stance)maxStanceError=Math.max(maxStanceError,f.error);curl=Math.max(curl,f.curl);lift=Math.max(lift,f.lift);}finite&&=JSON.stringify(d).indexOf('null')===-1;previous=d;}
 const walking=G.geckoDebug(g),otherIndependent=beforeOther.equals(other.getObjectByName('fore_L_lower').matrixWorld),last={...pose,x:240*.012,y:.45*Math.sin(240/90)};
 for(let i=1;i<=90;i++)G.animateGecko(g,6+i/60,last);const settled=G.geckoDebug(g);for(let i=1;i<=90;i++)G.animateGecko(g,7.5+i/60,last);const stopped=G.geckoDebug(g),stoppedTravel=stopped.travel-settled.travel,stoppedFootError=Math.max(...stopped.feet.map((f,n)=>new T.Vector3().fromArray(f.ankle).distanceTo(new T.Vector3().fromArray(settled.feet[n].ankle))));
 let burstStanceError=0,skinMinZ=Infinity,skinMinimum=null;
 for(const fps of [30,60]){let time=20+fps;G.animateGecko(g,time,pose);for(let i=1;i<=fps*2;i++){const t=i/fps,theta=Math.min(Math.PI/2,Math.max(0,t-.5)*1.3),x=t<.5?t*12:6+Math.sin(theta)*2,y=t<.5?0:2-2*Math.cos(theta);G.animateGecko(g,time+t,{...pose,x,y,heading:theta,mode:t<.5?'strike':'return'});const d=G.geckoDebug(g);for(const f of d.feet)if(f.stance)burstStanceError=Math.max(burstStanceError,f.error);if(i%15===0){skin.skeleton.update();for(let v=0;v<skin.geometry.attributes.position.count;v+=25){const pt=new T.Vector3().fromBufferAttribute(skin.geometry.attributes.position,v);skin.applyBoneTransform(v,pt).applyMatrix4(skin.matrixWorld);if(pt.z<skinMinZ){skinMinZ=pt.z;skinMinimum={fps,i,v,point:pt.toArray(),joints:[0,1,2,3].map(n=>({bone:skin.skeleton.bones[skin.geometry.attributes.skinIndex.getComponent(v,n)].name,weight:skin.geometry.attributes.skinWeight.getComponent(v,n)}))};}finite&&=Number.isFinite(pt.x+pt.y+pt.z);}}}}
 G.animateGecko(g,100,pose);for(let i=1;i<=54;i++)G.animateGecko(g,100+i/60,{...pose,mode:'warning',heading:Math.PI});const aimed=G.geckoDebug(g);G.animateGecko(g,110,pose);for(let i=1;i<=120;i++)G.animateGecko(g,110+i/60,{...pose,x:-i*.015,mode:'return'});const backing=G.geckoDebug(g);
 G.animateGecko(g,10,{...pose,x:0,y:0});draw();const result={meshes:meshes.length,bones:initial.bones,triangles:skin.geometry.index.count/3,textured:!!skin.material.map&&!!skin.material.normalMap,independentSkeleton:skin.skeleton!==otherSkin.skeleton&&skin.skeleton.bones[0]!==otherSkin.skeleton.bones[0],otherIndependent,independentMaterial:skin.material!==otherSkin.material,stableError,maxStanceError,burstStanceError,skinMinZ,skinMinimum,steps,curl,lift,finite,stoppedTravel,stoppedFootError,tailLag:walking.head[0]-walking.tail[0],aimedHeading:aimed.heading,backing:backing.backing,backingBodyLength:backing.head[0]-backing.tail[0],idle,walking,stopped};return result;
},auditScale);
await p.screenshot({path:'artifacts/gecko-game-rest.png'});
await p.evaluate(()=>{const{G,g,pose,draw}=window.__geckoReview;for(let i=1;i<=100;i++)G.animateGecko(g,10+i/60,{...pose,x:i*.013,y:.3*Math.sin(i/55),mode:'return'});draw(1.3,.3*Math.sin(100/55));});await p.screenshot({path:'artifacts/gecko-game-walk.png'});
if(process.env.GECKO_RECORD){const video=await p.evaluate(async()=>{const{g,G,renderer,draw}=window.__geckoReview,stream=renderer.domElement.captureStream(24),chunks=[],rec=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8',videoBitsPerSecond:2000000});const done=new Promise(resolve=>rec.onstop=resolve);rec.ondataavailable=e=>chunks.push(e.data);rec.start();const start=performance.now();await new Promise(resolve=>{function frame(now){const t=(now-start)/1000;let x=Math.min(t,2)*.7,y=0,mode='return',heading=0;if(t>=2&&t<2.8)mode='warning';else if(t>=2.8&&t<3.3){x=1.4+(t-2.8)*6;mode='strike';}else if(t>=3.3){x=4.4-Math.max(0,t-3.6)*.8;mode=t<3.6?'idle':'return';}G.animateGecko(g,200+t,{x,y,z:0,heading,mode});draw(x,y);if(t<6)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});rec.stop();await done;stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer()));});await fs.writeFile('artifacts/gecko-motion-review.webm',Buffer.from(video));}
const retry=await b.newPage();await retry.route('**/gecko-audit-preview',r=>r.fulfill({contentType:'text/html',body:'<body></body>'}));let attempt=0;await retry.route('**/models/gecko.glb',r=>++attempt===1?r.fulfill({status:503,body:'audit intentional failure'}):r.continue());await retry.goto(url+'/gecko-audit-preview');results.failureAndRetry=await retry.evaluate(async()=>{const G=await import('/src/gecko.ts');let rejected=false;try{await G.loadGecko();}catch{rejected=true;}await G.loadGecko();const g=G.createGecko();G.animateGecko(g,0,{x:0,y:0,z:0,heading:0,mode:'idle'});const good=G.geckoDebug(g).bones===68;G.disposeGecko(g);return rejected&&good&&G.geckoDebug(g)===null;});
await fs.writeFile('assets/gecko-source/game/browser_audit.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({results,errors},null,2));await b.close();
if(errors.length||!results.failureAndRetry||!results.independentMaterial||!results.backing||results.backingBodyLength<2||Math.abs(results.aimedHeading-Math.PI)>.15||!results.textured||!results.independentSkeleton||!results.otherIndependent||!results.finite||results.stableError>.015||results.maxStanceError>.015||results.burstStanceError>.045||results.skinMinZ<-.035||results.steps<8||results.curl<.1||results.lift<.02||results.stoppedFootError>.015||Math.abs(results.stoppedTravel)>1e-8)process.exitCode=1;
