import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const base=process.env.GEJI_AUDIT_URL??'http://127.0.0.1:5173',out='assets/geji-source/game';
const browser=await chromium.launch({headless:true}),p=await browser.newPage({viewport:{width:1200,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/geji-review',r=>r.fulfill({contentType:'text/html',body:'<body style="margin:0"></body>'}));await p.goto(base+'/geji-review');
const result=await p.evaluate(async()=>{
 const T=await import('/node_modules/three/build/three.module.js'),G=await import('/src/geji.ts');await G.loadGeji();const g=G.createGeji(),other=G.createGeji(),pose={x:0,y:0,z:0,heading:0};G.animateGeji(g,0,pose);G.animateGeji(other,0,{...pose,x:20});
 const scene=new T.Scene();scene.background=new T.Color('#454a48');scene.add(g,new T.HemisphereLight('#fff4dc','#747e78',2));const light=new T.DirectionalLight(0xffffff,2.4);light.position.set(2,-4,6);scene.add(light);
 const ground=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:'#898c83',roughness:1}));ground.position.z=-.005;scene.add(ground);
 const cam=new T.PerspectiveCamera(38,1.5,.1,100),renderer=new T.WebGLRenderer({antialias:true});cam.up.set(0,0,1);renderer.setSize(1200,800);renderer.toneMapping=T.ACESFilmicToneMapping;document.body.append(renderer.domElement);
 const draw=(x=0,y=0)=>{cam.position.set(x+.4,y-4.8,4.1);cam.lookAt(x-1.1,y,0);renderer.render(scene,cam);};
 const distance=(a,b)=>Math.hypot(...a.map((v,i)=>v-b[i]));let skin;g.traverse(o=>{if(o.isSkinnedMesh)skin=o;});const otherSkin=other.getObjectByName(skin.name),initial=G.gejiDebug(g),otherBefore=other.getObjectByName('leg_05_L_02').matrixWorld.clone();
 let stableError=0;for(let i=1;i<=60;i++){G.animateGeji(g,i/60,pose);const d=G.gejiDebug(g);stableError=Math.max(stableError,...d.feet.map((f,n)=>distance(f.foot,initial.feet[n].foot)));}
 const cases=[];let skinMinZ=Infinity;
 for(const fps of [30,60])for(const speed of [.5,18/3.9,5.64]){
  const start=10+fps+speed;G.animateGeji(g,start,pose);const beforeSteps=G.gejiDebug(g).feet.map(f=>f.steps);let previous=G.gejiDebug(g),maxSkate=0,maxContact=0,maxLength=0,minStance=30,maxLift=0,minKnee=Infinity,finite=true;
  for(let i=1;i<=fps*3;i++){
   G.animateGeji(g,start+i/fps,{...pose,x:speed*i/fps});const d=G.gejiDebug(g);let stance=0;
   for(let n=0;n<30;n++){const f=d.feet[n],prev=previous.feet[n];finite&&=[...f.foot,...f.knee].every(Number.isFinite);maxLength=Math.max(maxLength,Math.abs(distance(f.hip,f.knee)-f.l1),Math.abs(distance(f.knee,f.ankle)-f.l2));minKnee=Math.min(minKnee,f.knee[2]);maxLift=Math.max(maxLift,f.lift);if(f.stance){stance++;maxContact=Math.max(maxContact,distance(f.anchor,f.foot));if(prev.stance)maxSkate=Math.max(maxSkate,distance(prev.foot,f.foot));}}
   minStance=Math.min(minStance,stance);previous=d;
   if(i%fps===0){g.updateMatrixWorld(true);skin.skeleton.update();for(let v=0;v<skin.geometry.attributes.position.count;v+=17){const pt=new T.Vector3().fromBufferAttribute(skin.geometry.attributes.position,v);skin.applyBoneTransform(v,pt).applyMatrix4(skin.matrixWorld);skinMinZ=Math.min(skinMinZ,pt.z);}}
  }
  const walking=G.gejiDebug(g),stop={...pose,x:speed*3};for(let i=1;i<=fps;i++)G.animateGeji(g,start+3+i/fps,stop);const settled=G.gejiDebug(g);for(let i=1;i<=fps;i++)G.animateGeji(g,start+4+i/fps,stop);const stopped=G.gejiDebug(g);
  cases.push({fps,speed,maxSkate,maxContact,maxLength,minStance,minKnee,maxLift,finite,allLegsStepped:walking.feet.every((f,n)=>f.steps>beforeSteps[n]),stoppedTravel:stopped.travel-settled.travel,stoppedFootError:Math.max(...stopped.feet.map((f,n)=>distance(f.foot,settled.feet[n].foot))),stoppedStance:stopped.feet.filter(f=>f.stance).length});
 }
 let narrowContact=0,narrowOutside=0;const floor=(x,y)=>Math.abs(y)<.9?0:null;G.animateGeji(g,200,pose,floor);for(let i=1;i<=120;i++){G.animateGeji(g,200+i/60,{...pose,x:i*.04},floor);for(const f of G.gejiDebug(g).feet)if(f.stance){narrowContact=Math.max(narrowContact,distance(f.foot,f.anchor));narrowOutside=Math.max(narrowOutside,Math.abs(f.foot[1])-.9);}}
 const resetBefore=G.gejiDebug(g).resets;G.animateGeji(g,0,{...pose,x:10,active:false});G.animateGeji(g,.01,pose);const reset=G.gejiDebug(g);
 draw();window.__gejiReview={T,G,g,scene,cam,renderer,draw,pose};return{bones:initial.bones,feet:initial.feet.length,triangles:skin.geometry.index.count/3,independentSkeleton:skin.skeleton!==otherSkin.skeleton&&skin.skeleton.bones[0]!==otherSkin.skeleton.bones[0],independentMaterial:skin.material!==otherSkin.material,otherUnchanged:otherBefore.equals(other.getObjectByName('leg_05_L_02').matrixWorld),stableError,cases,narrowContact,narrowOutside,skinMinZ,reset:reset.resets>resetBefore&&reset.travel===0&&reset.feet.every(f=>f.stance)};
});
await p.screenshot({path:'artifacts/geji-game-rest.png'});
for(const [k,frame] of [20,25,30].entries()){await p.evaluate(n=>{const {G,g,pose,draw}=window.__gejiReview;G.animateGeji(g,300,pose);for(let i=1;i<=n;i++)G.animateGeji(g,300+i/60,{...pose,x:i*.035});draw(n*.035);},frame);await p.screenshot({path:`artifacts/geji-game-walk-${k}.png`});}
await p.evaluate(()=>{const{cam,renderer,scene}=window.__gejiReview;cam.position.set(0,-5,.7);cam.lookAt(-.2,0,.3);renderer.render(scene,cam);});await p.screenshot({path:'artifacts/geji-game-side.png'});
const retry=await browser.newPage();await retry.route('**/geji-review',r=>r.fulfill({contentType:'text/html',body:'<body></body>'}));let attempt=0;await retry.route('**/models/geji.glb',r=>++attempt===1?r.fulfill({status:503,body:'intentional load failure'}):r.continue());await retry.goto(base+'/geji-review');result.failureRetry=await retry.evaluate(async()=>{const G=await import('/src/geji.ts');let failed=false;try{await G.loadGeji();}catch{failed=true;}await G.loadGeji();const g=G.createGeji();G.animateGeji(g,0,{x:0,y:0,z:0,heading:0});const loaded=G.gejiDebug(g).feet.length===30;G.disposeGeji(g);return failed&&loaded&&G.gejiDebug(g)===null;});await retry.close();
if(process.env.GEJI_RECORD){const video=await p.evaluate(async()=>{const{G,g,pose,draw,renderer}=window.__gejiReview,stream=renderer.domElement.captureStream(30),chunks=[],rec=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8',videoBitsPerSecond:3500000}),done=new Promise(resolve=>rec.onstop=resolve);rec.ondataavailable=e=>chunks.push(e.data);rec.start();let t=0;await new Promise(resolve=>{function frame(){const x=t<1?0:t<4?(t-1)*1.5:4.5;G.animateGeji(g,400+t,{...pose,x});draw(x);t+=1/30;if(t<=5.5)requestAnimationFrame(frame);else resolve();}frame();});rec.stop();await done;stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer()));});await fs.writeFile('artifacts/geji-motion-review.webm',Buffer.from(video));}
await fs.writeFile(out+'/browser_audit.json',JSON.stringify({result,errors},null,2));console.log(JSON.stringify({result,errors},null,2));await browser.close();
if(errors.length||result.bones!==134||result.feet!==30||!result.independentSkeleton||!result.independentMaterial||!result.otherUnchanged||!result.failureRetry||!result.reset||result.stableError>1e-5||result.skinMinZ<-.025||result.narrowContact>.02||result.narrowOutside>.01||result.cases.some(c=>!c.finite||!c.allLegsStepped||c.maxSkate>.02||c.maxContact>.02||c.maxLength>.0001||c.minStance<12||c.minKnee<.05||c.maxLift<.03||c.stoppedFootError>.0001||c.stoppedStance!==30||c.stoppedTravel!==0))process.exitCode=1;
