import * as THREE from 'three';
import { animateAnimal, createAnimal, loadAnimals } from './animals';

type ChapterSave = { version:1; unlockedChapter:number; currentChapter:number; survivors:number; instar:number; bodySize:number; injuries:string[] };
type Gap = { x:number; y:number; width:number; side:-1|1; depth:number };
type CentipedeState = 'patrol'|'warning'|'chase'|'recover';
const SAVE_KEY='g-survival-progress-v1';
const clamp=(v:number,lo:number,hi:number)=>Math.max(lo,Math.min(hi,v));
const gaps:Gap[]=[
 {x:4,y:17,width:1.32,side:-1,depth:3.6},{x:10,y:29,width:.78,side:1,depth:2.8},
 {x:4,y:38,width:1.24,side:-1,depth:3.8},{x:10,y:57,width:.72,side:1,depth:2.7},
 {x:4,y:70,width:1.18,side:-1,depth:3.5},{x:10,y:84,width:.76,side:1,depth:2.6},
];

export function readProgress():ChapterSave{try{const v=JSON.parse(localStorage.getItem(SAVE_KEY)??'');if(v?.version===1&&Number.isInteger(v.survivors))return v;}catch{}return{version:1,unlockedChapter:1,currentChapter:1,survivors:24,instar:1,bodySize:.75,injuries:[]};}
export function completeChapterOne(survivors:number){const s:ChapterSave={...readProgress(),unlockedChapter:2,currentChapter:2,survivors:Math.max(1,survivors),instar:3,bodySize:1.02};localStorage.setItem(SAVE_KEY,JSON.stringify(s));}

export async function mountChapterTwo(){
 const save=readProgress();if(!location.search.includes('from=chapter1')&&save.unlockedChapter<2){save.survivors=8;save.instar=3;save.bodySize=1.02;}
 document.title='G-survival — 第2章 壁の中';document.querySelector('#app')!.innerHTML=`<canvas id="shaft"></canvas><div class="vignette"></div><header><span class="mark">G-survival <small>— 隙間の生 —</small></span><span class="chapter">CHAPTER 02 / 壁の中</span></header><div id="entry"><div class="eyebrow">LATE SUMMER / THIRD INSTAR</div><h1>壁の中</h1><p class="story">白い帯は、いつの間にか薄くなった。<br>身体は大きくなり、昨日までの隙間に、胸が触れる。</p><p class="goal"><b>下へ。</b><br>壁の中を、一階分だけ降りる。<br>兄弟の気配は遠ざかり、脚の多い影が近づく。</p><button id="begin" disabled>壁の中を読み込み中…</button><small>この壁へ入った群れ: ${save.survivors}匹</small></div><aside id="hud"><div id="population">${save.survivors} 匹</div><div id="objective">断熱材の層</div></aside><div id="warning"></div><div id="controls">WASD / 矢印：這う　·　Shift：走る　·　左長押し：隙間を測る</div><div id="ending" hidden><div class="eyebrow">CHAPTER 02 / FOUNDATION</div><h2></h2><p></p><button id="again">もう一度、壁の中へ ↗</button></div><footer><span>PERIPLANETA FULIGINOSA</span><span>02 — IN THE WALL</span></footer>`;
 await loadAnimals();
 const canvas=document.querySelector<HTMLCanvasElement>('#shaft')!,renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#0b0e10');scene.fog=new THREE.FogExp2('#0b0e10',.025);scene.add(new THREE.HemisphereLight('#9aa8ae','#261d1a',2.1));
 const lamp=new THREE.PointLight('#d1aa82',35,18);scene.add(lamp);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,180);
 const wallMat=new THREE.MeshStandardMaterial({color:'#2c3738',roughness:.94}),timber=new THREE.MeshStandardMaterial({color:'#55463b',roughness:.88}),voidMat=new THREE.MeshStandardMaterial({color:'#071012',roughness:1}),copper=new THREE.MeshStandardMaterial({color:'#93634a',roughness:.48,metalness:.35}),iron=new THREE.MeshStandardMaterial({color:'#354447',roughness:.62,metalness:.55}),insulation=new THREE.MeshStandardMaterial({color:'#71654d',roughness:1});
 function box(x:number,y:number,z:number,w:number,h:number,d:number,mat:THREE.Material){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,-y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m;}
 function pipeAt(x:number,y:number,len:number,r:number,mat:THREE.Material=copper){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,len,12),mat);m.position.set(x,-y,.72);m.castShadow=true;scene.add(m);return m;}
 box(7,48,-.6,15,98,1,wallMat);for(const x of [1,7,13])box(x,48,.25,.58,98,.62,timber);for(let y=7;y<92;y+=8)box(7,y,.2,15,.32,.55,timber);
 for(let y=5;y<27;y+=3.2)box(3+(y%2),y,.25,4.8,.42,.55,insulation);
 pipeAt(10.9,48,98,.29);pipeAt(3.2,49,72,.18,iron);for(const y of [33,60,78]){const cross=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,5.8,10),copper);cross.rotation.z=Math.PI/2;cross.position.set(8,-y,.7);scene.add(cross);}
 for(const gap of gaps){const cx=gap.side<0?gap.x-gap.depth/2:gap.x+gap.depth/2;box(cx,gap.y,.28,gap.depth,gap.width,.9,voidMat);box(cx,gap.y-gap.width/2-.16,.56,gap.depth+.2,.18,.62,timber);box(cx,gap.y+gap.width/2+.16,.56,gap.depth+.2,.18,.62,timber);const rim=new THREE.Mesh(new THREE.BoxGeometry(.16,gap.width+.36,.12),copper);rim.position.set(gap.side<0?3.92:10.08,-gap.y,.84);scene.add(rim);}
 for(const y of [88,91,94])box(7,y,.18,15,.48,.64,timber);
 const hero=createAnimal('roach',save.bodySize);scene.add(hero);
 const companions=[-1,1,2].map((side,i)=>{const g=createAnimal('roach',save.bodySize*.92);scene.add(g);return{g,side,delay:i*.18};});
 const centipede=new THREE.Group(),segments:THREE.Mesh[]=[];const centMat=new THREE.MeshStandardMaterial({color:'#704631',roughness:.76}),headMat=new THREE.MeshStandardMaterial({color:'#39251c',roughness:.68});
 for(let n=0;n<9;n++){const segment=new THREE.Mesh(new THREE.SphereGeometry(n===0?.27:.22,10,6),n===0?headMat:centMat);segment.scale.set(1.32,.72,.28);segment.position.set(-n*.31,Math.sin(n*.9)*.035,.13);centipede.add(segment);segments.push(segment);for(const side of [-1,1]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.014,.014,.3,4),centMat);leg.rotation.z=Math.PI/2.55*side;leg.position.set(side*.22,0,.035);segment.add(leg);}}scene.add(centipede);
 const geji=new THREE.Group(),gejiMat=new THREE.MeshStandardMaterial({color:'#4f5350',roughness:.82});for(let n=0;n<12;n++){const body=new THREE.Mesh(new THREE.SphereGeometry(.12,8,5),gejiMat);body.scale.set(1.5,.62,.2);body.position.set(-n*.18,0,.1);geji.add(body);for(const side of [-1,1]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.008,.008,.78,4),gejiMat);leg.rotation.z=side*Math.PI/2.25;leg.position.set(0,side*.27,.02);body.add(leg);}}scene.add(geji);
 const keys=new Set<string>();let started=false,ended=false,probe=false,last=performance.now(),startedAt=0,survivors=save.survivors,invulnerable=0,lossNotice=0;const player={x:7,y:3,angle:-Math.PI/2};const checkpoint={x:7,y:3};const enemy={x:7,y:34,state:'patrol' as CentipedeState,timer:0,targetY:34};
 addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();keys.add(e.code);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());addEventListener('pointerdown',e=>{if(e.button===0&&!(e.target as HTMLElement).closest('button'))probe=true;});addEventListener('pointerup',()=>probe=false);
 const resize=()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();};addEventListener('resize',resize);resize();
 const begin=document.querySelector<HTMLButtonElement>('#begin')!;begin.disabled=false;begin.innerHTML='壁の中へ入る <span>↓</span>';begin.onclick=()=>{started=true;startedAt=performance.now();document.querySelector('#entry')!.classList.add('gone');};document.querySelector<HTMLButtonElement>('#again')!.onclick=()=>location.reload();
 const nearGap=()=>gaps.find(g=>Math.abs(player.y-g.y)<g.width*.5+.18&&Math.abs(player.x-g.x)<g.depth+.5);
 const sheltered=()=>{const g=nearGap();return !!g&&g.width>=save.bodySize&&(g.side<0?player.x<3.8:player.x>10.2);};
 function move(dt:number){const dx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),dy=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),len=Math.hypot(dx,dy);if(!len)return 0;const speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')?3.6:2.6),step=speed*dt,nx=dx/len,ny=dy/len;let nextX=player.x+nx*step,nextY=clamp(player.y+ny*step,1,92);const gate=gaps.find(g=>Math.abs(nextY-g.y)<g.width*.5+.18&&((g.side<0&&nextX<4)||(g.side>0&&nextX>10)));if(nextX<4||nextX>10){if(!gate||gate.width<save.bodySize)nextX=clamp(nextX,4,10);else nextX=clamp(nextX,gate.side<0?4-gate.depth:4,gate.side>0?10+gate.depth:10);}player.x=nextX;player.y=nextY;player.angle=Math.atan2(-ny,nx);return speed;}
 function updateEnemy(dt:number){enemy.timer+=dt;if(enemy.state==='patrol'){enemy.y=34+(1-Math.abs((enemy.timer*2.1%44)-22));if(Math.hypot(enemy.x-player.x,enemy.y-player.y)<7.5&&!sheltered()){enemy.state='warning';enemy.timer=0;enemy.targetY=player.y;}}else if(enemy.state==='warning'){if(sheltered()){enemy.state='recover';enemy.timer=0;}else if(enemy.timer>=.6){enemy.state='chase';enemy.timer=0;}}else if(enemy.state==='chase'){if(sheltered()){enemy.state='recover';enemy.timer=0;}else{const dx=player.x-enemy.x,dy=player.y-enemy.y,distance=Math.hypot(dx,dy),d=distance||1,step=Math.min(distance,3.9*dt);enemy.x+=dx/d*step;enemy.y+=dy/d*step;if(distance<.58&&invulnerable<=0){survivors--;lossNotice=2.5;invulnerable=1.2;player.x=checkpoint.x;player.y=checkpoint.y;enemy.state='recover';enemy.timer=0;if(survivors<=0)finish(false);}}}else if(enemy.timer>=1.6){enemy.state='patrol';enemy.timer=0;}}
 function finish(won:boolean){ended=true;const end=document.querySelector<HTMLElement>('#ending')!;end.hidden=false;end.querySelector('h2')!.textContent=won?'床下の冷たさ':'脚音だけが残った';end.querySelector('p')!.textContent=won?'キッチンの床板が、遠くで鳴った。':'Gの群れは、壁の途中で途絶えた。';}
 function render(now:number,speed:number){hero.position.set(player.x,-player.y,.72);animateAnimal(hero,now/1000,speed,player.angle);const scatter=Math.min(1,Math.max(0,(now-startedAt)/1800));companions.forEach(({g,side,delay},i)=>{if(scatter>=1){g.visible=false;return;}const t=Math.max(0,Math.min(1,scatter-delay));g.position.set(7+side*(.35+t*(2.8+i*.45)),-(3+t*(3.5+i*1.8)),.72);animateAnimal(g,now/1000,2.4,Math.atan2(-(3.5+i*1.8),side*(2.8+i*.45)));});segments.forEach((s,n)=>s.position.y=Math.sin(now*.006-n*.7)*.055);centipede.position.set(enemy.x,-enemy.y,.08);centipede.rotation.z=Math.atan2(-(player.y-enemy.y),player.x-enemy.x);const gejiPhase=(now/1000)%10,gejiX=gejiPhase<.65?-3:gejiPhase<4.2?-3+(gejiPhase-.65)*5.2:16;geji.visible=gejiPhase<4.2;geji.position.set(gejiX,-61,.09);geji.rotation.z=0;camera.position.set(7,-player.y+2.2,17);camera.lookAt(7,-player.y-2,0);lamp.position.set(player.x,-player.y+1,4);renderer.render(scene,camera);}
 function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;let speed=0;if(started&&!ended){invulnerable=Math.max(0,invulnerable-dt);lossNotice=Math.max(0,lossNotice-dt);speed=move(dt);if(player.y>12)checkpoint.y=Math.max(checkpoint.y,Math.floor(player.y/18)*18);updateEnemy(dt);if(player.y>=91)finish(true);const gap=nearGap(),tooNarrow=!!gap&&gap.width<save.bodySize,danger=enemy.state==='warning'||enemy.state==='chase',gejiWarning=player.y>54&&player.y<68&&((now/1000)%10)<.65;document.querySelector('#warning')!.textContent=lossNotice>0?'Gが1体、減りました':tooNarrow?'胸が擦れる。ここはもう通れない。':danger?(enemy.state==='warning'?'粉塵が、下から浮いた。':'ムカデの頭が、こちらへ向いた。'):gejiWarning?'配管の上で、細い脚音が増えていく。':probe&&gap?(gap.width>=save.bodySize?'触角の先に、身体を隠せる奥行きがある。':'触角が、奥で戻ってきた。'):'';document.querySelector('#population')!.textContent=survivors+' 匹';document.querySelector('#objective')!.textContent=player.y<28?'配線と間柱のシャフト':player.y<58?'湿った配管の分岐':player.y<82?'巾木の裏':'キッチンの床下';}render(now,speed);}
 if(import.meta.env.DEV&&new URLSearchParams(location.search).has('test'))Object.assign(window,{chapter2Test:{setPosition(x:number,y:number){player.x=x;player.y=y;},snapshot(){return{...player,survivors,enemy:{...enemy},sheltered:sheltered()};},setEnemy(state:CentipedeState,y:number,timer=0,x=7){enemy.state=state;enemy.x=x;enemy.y=y;enemy.timer=timer;}}});requestAnimationFrame(frame);
}
