import * as THREE from 'three';
import { animateAnimal, createAnimal, loadAnimals } from './animals';
import { animateCentipede, createCentipede, loadCentipede } from './centipede';
import { AudioEngine } from './audio';

type ChapterSave = { version:1; unlockedChapter:number; currentChapter:number; survivors:number; instar:number; bodySize:number; injuries:string[] };
type Gap = { x:number; y:number; width:number; side:-1|1; depth:number };
type CentipedeState = 'patrol'|'warning'|'chase'|'recover';
const SAVE_KEY='g-survival-progress-v1';
const clamp=(v:number,lo:number,hi:number)=>Math.max(lo,Math.min(hi,v));
const LEFT=4,RIGHT=28;
const gaps:Gap[]=[
 {x:4,y:17,width:1.4,side:-1,depth:3.6},{x:28,y:20,width:1.4,side:1,depth:3.2},
 {x:4,y:38,width:1.4,side:-1,depth:3.8},{x:28,y:39,width:1.4,side:1,depth:3.2},
 {x:4,y:55,width:1.4,side:-1,depth:3.5},{x:28,y:57,width:1.4,side:1,depth:3.2},
 {x:4,y:70,width:1.4,side:-1,depth:3.5},{x:28,y:75,width:1.4,side:1,depth:3.2},
 {x:4,y:80,width:1.4,side:-1,depth:3.5},{x:28,y:85,width:1.4,side:1,depth:3.2},
 {x:4,y:29,width:.78,side:-1,depth:2.8},
];
// AI provisional dimensions: full-height baffles force lateral detours; low debris can be climbed.
const terrain=[{x:4,y:24,w:17,h:1.2,top:3,solid:true},{x:12,y:46,w:16,h:1.2,top:3,solid:true},{x:4,y:66,w:15,h:1.2,top:3,solid:true},{x:14,y:82,w:14,h:1.2,top:3,solid:true},
 {x:9,y:14,w:5,h:5,top:1.3,solid:false},{x:17,y:34,w:5,h:5,top:1.6,solid:false},{x:10,y:54,w:5,h:4,top:1.2,solid:false}];
const blocked=(x:number,y:number,r=.35,enemy=false)=>terrain.some(o=>(o.solid||enemy)&&x>o.x-r&&x<o.x+o.w+r&&y>o.y-r&&y<o.y+o.h+r);
const heightAt=(x:number,y:number)=>terrain.reduce((z,o)=>o.solid?z:Math.max(z,o.top*clamp(Math.min(x-o.x,o.x+o.w-x,y-o.y,o.y+o.h-y)/1.2,0,1)),0);
const clearLine=(ax:number,ay:number,bx:number,by:number)=>{const n=Math.ceil(Math.hypot(bx-ax,by-ay)*4);for(let i=0;i<=n;i++)if(blocked(ax+(bx-ax)*i/Math.max(n,1),ay+(by-ay)*i/Math.max(n,1),.2,true))return false;return true;};

export function readProgress():ChapterSave{try{const v=JSON.parse(localStorage.getItem(SAVE_KEY)??'');if(v?.version===1&&Number.isInteger(v.survivors))return v;}catch{}return{version:1,unlockedChapter:1,currentChapter:1,survivors:24,instar:1,bodySize:.75,injuries:[]};}
export function completeChapterOne(survivors:number){const s:ChapterSave={...readProgress(),unlockedChapter:2,currentChapter:2,survivors:Math.max(1,survivors),instar:3,bodySize:1.02};localStorage.setItem(SAVE_KEY,JSON.stringify(s));}

export async function mountChapterTwo(){
 const save=readProgress();if(!location.search.includes('from=chapter1')&&save.unlockedChapter<2){save.survivors=8;save.instar=3;save.bodySize=1.02;}
 document.title='G-survival — 第2章 壁の中';document.querySelector('#app')!.innerHTML=`<canvas id="shaft"></canvas><div class="vignette"></div><header><span class="mark">G-survival <small>— 隙間の生 —</small></span><span class="chapter">CHAPTER 02 / 壁の中</span></header><div id="entry"><div class="eyebrow">LATE SUMMER / THIRD INSTAR</div><h1>壁の中</h1><p class="story">白い帯は、いつの間にか薄くなった。<br>身体は大きくなり、昨日までの隙間に、胸が触れる。</p><p class="goal"><b>下へ。</b><br>壁の中を、一階分だけ降りる。<br>兄弟の気配は遠ざかり、脚の多い影が近づく。</p><button id="begin" disabled>壁の中を読み込み中…</button><small>この壁へ入った群れ: ${save.survivors}匹</small></div><aside id="hud"><div id="population">${save.survivors} 匹</div><div id="objective">断熱材の層</div></aside><div id="warning"></div><div id="controls">WASD / 矢印：這う　·　Shift：走る　·　左長押し：隙間を測る</div><div id="ending" hidden><div class="eyebrow">CHAPTER 02 / FOUNDATION</div><h2></h2><p></p><button id="again">もう一度、壁の中へ ↗</button></div><footer><span>PERIPLANETA FULIGINOSA</span><span>02 — IN THE WALL</span></footer>`;
 await Promise.all([loadAnimals(),loadCentipede()]);
 const canvas=document.querySelector<HTMLCanvasElement>('#shaft')!,renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#0b0e10');scene.fog=new THREE.FogExp2('#0b0e10',.025);scene.add(new THREE.HemisphereLight('#9aa8ae','#261d1a',2.1));
 const lamp=new THREE.PointLight('#d1aa82',35,18);scene.add(lamp);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,180);
 const wallMat=new THREE.MeshStandardMaterial({color:'#2c3738',roughness:.94}),timber=new THREE.MeshStandardMaterial({color:'#55463b',roughness:.88}),voidMat=new THREE.MeshStandardMaterial({color:'#071012',roughness:1}),copper=new THREE.MeshStandardMaterial({color:'#93634a',roughness:.48,metalness:.35}),iron=new THREE.MeshStandardMaterial({color:'#354447',roughness:.62,metalness:.55}),insulation=new THREE.MeshStandardMaterial({color:'#71654d',roughness:1});
 function box(x:number,y:number,z:number,w:number,h:number,d:number,mat:THREE.Material){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,-y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m;}
 function pipeAt(x:number,y:number,len:number,r:number,mat:THREE.Material=copper){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,len,12),mat);m.position.set(x,-y,.72);m.castShadow=true;scene.add(m);return m;}
 box(16,48,-.6,34,98,1,wallMat);for(const o of terrain){if(o.solid)box(o.x+o.w/2,o.y+o.h/2,o.top/2,o.w,o.h,o.top,timber);else{const geometry=new THREE.PlaneGeometry(o.w,o.h,20,20),positions=geometry.attributes.position;for(let i=0;i<positions.count;i++){const x=positions.getX(i)+o.x+o.w/2,y=-positions.getY(i)+o.y+o.h/2;positions.setXYZ(i,x,-y,heightAt(x,y));}geometry.computeVertexNormals();const mound=new THREE.Mesh(geometry,insulation);mound.castShadow=mound.receiveShadow=true;scene.add(mound);}}for(const x of [1,31])box(x,48,.25,.58,98,.62,timber);for(let y=7;y<92;y+=8)box(16,y,-.05,32,.32,.15,timber);
 for(let y=5;y<27;y+=3.2)box(3+(y%2),y,.25,4.8,.42,.55,insulation);
 pipeAt(10.9,48,98,.29);pipeAt(3.2,49,72,.18,iron);for(const y of [33,60,78]){const cross=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,5.8,10),copper);cross.rotation.z=Math.PI/2;cross.position.set(8,-y,.7);scene.add(cross);}
 for(const gap of gaps){const cx=gap.side<0?gap.x-gap.depth/2:gap.x+gap.depth/2;box(cx,gap.y,.28,gap.depth,gap.width,.9,voidMat);box(cx,gap.y-gap.width/2-.16,.56,gap.depth+.2,.18,.62,timber);box(cx,gap.y+gap.width/2+.16,.56,gap.depth+.2,.18,.62,timber);const rim=new THREE.Mesh(new THREE.BoxGeometry(.16,gap.width+.36,.12),copper);rim.position.set(gap.x+gap.side*.08,-gap.y,.84);scene.add(rim);}
 for(const y of [91,94])box(16,y,.18,34,.48,.64,timber);
 box(26,90,.22,4,3,.3,voidMat);box(26,93,1,5,.4,2,timber);
 const kitchenLight=new THREE.PointLight('#ffe1aa',18,10);kitchenLight.position.set(26,-91,2.5);scene.add(kitchenLight);
 const slipper=box(26,92,2.5,5,1.3,.3,voidMat);slipper.visible=false;
 const wind=box(16,61,.12,24,.12,.06,copper);wind.visible=false;
 const hero=createAnimal('roach',save.bodySize),heroSurface=new THREE.Group();heroSurface.add(hero);scene.add(heroSurface);
 const companions=[-1,1,2].map((side,i)=>{const g=createAnimal('roach',save.bodySize*.92);scene.add(g);return{g,side,delay:i*.18};});
 const centipede=createCentipede();scene.add(centipede);
 const geji=new THREE.Group(),gejiMat=new THREE.MeshStandardMaterial({color:'#4f5350',roughness:.82});for(let n=0;n<12;n++){const body=new THREE.Mesh(new THREE.SphereGeometry(.12,8,5),gejiMat);body.scale.set(1.5,.62,.2);body.position.set(-n*.18,0,.1);geji.add(body);for(const side of [-1,1]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.008,.008,.78,4),gejiMat);leg.rotation.z=side*Math.PI/2.25;leg.position.set(0,side*.27,.02);body.add(leg);}}scene.add(geji);
 const gecko=new THREE.Group(),geckoMat=new THREE.MeshStandardMaterial({color:'#8b8768',roughness:.9});const geckoBody=new THREE.Mesh(new THREE.SphereGeometry(.42,12,8),geckoMat);geckoBody.scale.set(2.2,.68,.2);gecko.add(geckoBody);const geckoHead=new THREE.Mesh(new THREE.SphereGeometry(.3,10,7),geckoMat);geckoHead.position.x=1.02;geckoHead.scale.set(1,.75,.25);gecko.add(geckoHead);for(const side of [-1,1])for(const x of [-.5,.45]){const foot=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.7,5),geckoMat);foot.rotation.z=side*Math.PI/2.25;foot.position.set(x,side*.28,.02);gecko.add(foot);}gecko.position.set(7,-77,.65);scene.add(gecko);
 const audio=new AudioEngine();const keys=new Set<string>();let started=false,ended=false,probe=false,last=performance.now(),startedAt=0,survivors=save.survivors,invulnerable=0,lossNotice=0,moltHold=0,molting=0,molted=save.bodySize>1.02,geckoTimer=0,geckoWarning=0,humanTimer=-1;let elapsed=0,gejiExposure=0;const geckoAttack={x:7,y:77,tx:7,ty:77,strike:0};let bodySize=save.bodySize;const player={x:7,y:3,angle:-Math.PI/2};const checkpoint={x:7,y:3};const enemy={x:7,y:34,state:'patrol' as CentipedeState,timer:0,targetY:34};
 addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();keys.add(e.code);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());addEventListener('pointerdown',e=>{if(e.button===0&&!(e.target as HTMLElement).closest('button'))probe=true;});addEventListener('pointerup',()=>probe=false);
 const resize=()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();};addEventListener('resize',resize);resize();
 const begin=document.querySelector<HTMLButtonElement>('#begin')!;begin.disabled=false;begin.innerHTML='壁の中へ入る <span>↓</span>';begin.onclick=()=>{started=true;startedAt=performance.now();document.querySelector('#entry')!.classList.add('gone');void audio.start();};document.querySelector<HTMLButtonElement>('#again')!.onclick=()=>location.reload();
 const nearGap=()=>gaps.find(g=>Math.abs(player.y-g.y)<g.width*.5+.18&&(player.x-g.x)*g.side>-.5&&(player.x-g.x)*g.side<g.depth+.5);
 const sheltered=()=>{const g=nearGap();return !!g&&g.width>=bodySize&&(player.x-g.x)*g.side>.2;};
 function move(dt:number){if(molting>0||humanTimer>=0)return 0;const dx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),dy=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),len=Math.hypot(dx,dy);if(!len)return 0;const speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')?3.6:2.6),step=speed*dt,nx=dx/len,ny=dy/len;let nextX=player.x+nx*step,nextY=clamp(player.y+ny*step,1,92);const gate=gaps.find(g=>Math.abs(nextY-g.y)<Math.max(.08,(g.width-bodySize)*.5+.1)&&((g.side<0&&nextX<LEFT)||(g.side>0&&nextX>RIGHT)));
 if(nextX<LEFT||nextX>RIGHT){if(!gate||gate.width<bodySize){nextX=clamp(nextX,LEFT,RIGHT);if(player.x<LEFT||player.x>RIGHT){nextX=player.x+nx*step;nextY=player.y;}}else nextX=clamp(nextX,gate.side<0?LEFT-gate.depth:LEFT,gate.side>0?RIGHT+gate.depth:RIGHT);}
 if(!blocked(nextX,player.y))player.x=nextX;if(!blocked(player.x,nextY))player.y=nextY;player.angle=Math.atan2(-ny,nx);return speed;}
 function updateEnemy(dt:number){enemy.timer+=dt;if(enemy.state==='patrol'){const patrolY=34+Math.sin(enemy.timer*.12)*7;if(!blocked(enemy.x,patrolY,.4,true))enemy.y=patrolY;if(Math.hypot(enemy.x-player.x,enemy.y-player.y)<7.5&&!sheltered()&&clearLine(enemy.x,enemy.y,player.x,player.y)){enemy.state='warning';enemy.timer=0;enemy.targetY=player.y;}}else if(enemy.state==='warning'){if(sheltered()){enemy.state='recover';enemy.timer=0;}else if(enemy.timer>=.6){enemy.state='chase';enemy.timer=0;}}else if(enemy.state==='chase'){if(sheltered()){enemy.state='recover';enemy.timer=0;}else{const dx=player.x-enemy.x,dy=player.y-enemy.y,distance=Math.hypot(dx,dy),d=distance||1,step=Math.min(distance,3.9*dt);if(!blocked(enemy.x+dx/d*step,enemy.y,.4,true))enemy.x+=dx/d*step;if(!blocked(enemy.x,enemy.y+dy/d*step,.4,true))enemy.y+=dy/d*step;if(distance<.58&&heightAt(player.x,player.y)<.3&&invulnerable<=0){survivors--;lossNotice=2.5;invulnerable=1.2;player.x=checkpoint.x;player.y=checkpoint.y;enemy.state='recover';enemy.timer=0;if(survivors<=0)finish(false);}}}else if(enemy.timer>=1.6){enemy.state='patrol';enemy.timer=0;}}
 function lose(){if(invulnerable>0)return;survivors--;lossNotice=2.5;invulnerable=1.2;player.x=checkpoint.x;player.y=checkpoint.y;enemy.state='recover';enemy.timer=0;if(survivors<=0)finish(false);}
 function updateHazards(dt:number,now:number){
  const phase=now%10,gejiX=LEFT-3+(phase-.9)*8;
  gejiExposure=player.y>54&&player.y<68?gejiExposure+dt:0;
  if(phase>=.9&&phase<4.8&&gejiExposure>=.9&&!sheltered()&&Math.abs(player.y-61)<.5&&player.x<=gejiX+.25&&player.x>=gejiX-2.4&&heightAt(player.x,player.y)<.3)lose();
  if(player.y>72&&player.y<84&&!sheltered()&&geckoWarning<=0&&geckoAttack.strike<=0){geckoTimer+=dt;if(geckoTimer>=1.1){geckoWarning=.9;geckoTimer=0;geckoAttack.tx=player.x;geckoAttack.ty=player.y;}}else geckoTimer=0;
  if(geckoWarning>0){geckoWarning-=dt;if(geckoWarning<=0)geckoAttack.strike=.65;}
  if(geckoAttack.strike>0){geckoAttack.strike-=dt;const dx=geckoAttack.tx-geckoAttack.x,dy=geckoAttack.ty-geckoAttack.y,d=Math.hypot(dx,dy)||1,step=Math.min(d,12*dt);if(!blocked(geckoAttack.x+dx/d*step,geckoAttack.y+dy/d*step,.45,true)){geckoAttack.x+=dx/d*step;geckoAttack.y+=dy/d*step;}if(!sheltered()&&Math.hypot(player.x-geckoAttack.x,player.y-geckoAttack.y)<.7)lose();}
  if(!molted&&player.y>67&&player.y<73&&sheltered()&&keys.has('Space'))moltHold+=dt;else moltHold=0;
  if(!molted&&moltHold>=3){molting=3.2;moltHold=0;}
  if(molting>0){molting-=dt;if(molting<=0){molted=true;bodySize=1.2;save.bodySize=bodySize;save.instar=4;localStorage.setItem(SAVE_KEY,JSON.stringify(save));}}
  if(player.y>=89&&player.x>=24&&humanTimer<0)humanTimer=0;
  if(humanTimer>=0){humanTimer+=dt;if(humanTimer>=3.2)finish(true);}
 }
 function finish(won:boolean){if(ended)return;ended=true;const end=document.querySelector<HTMLElement>('#ending')!;end.hidden=false;end.querySelector('h2')!.textContent=won?'床下の冷たさ':'脚音だけが残った';end.querySelector('p')!.textContent=won?'床板が震え、スリッパの影が隙間を横切った。次の闇が、台所に続いている。':'Gの群れは、壁の途中で途絶えた。';}
 function render(now:number,speed:number){heroSurface.position.set(player.x,-player.y,.72+heightAt(player.x,player.y));const slopeX=(heightAt(player.x+.05,player.y)-heightAt(player.x-.05,player.y))/.1,slopeY=(heightAt(player.x,player.y+.05)-heightAt(player.x,player.y-.05))/.1;heroSurface.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),new THREE.Vector3(-slopeX,slopeY,1).normalize());animateAnimal(hero,now/1000,speed,player.angle,molting>0?(1-molting/3.2):molted?.3:0);const scatter=Math.min(1,Math.max(0,(now-startedAt)/1800));companions.forEach(({g,side,delay},i)=>{if(scatter>=1){g.visible=false;return;}const t=Math.max(0,Math.min(1,scatter-delay));g.position.set(7+side*(.35+t*(2.8+i*.45)),-(3+t*(3.5+i*1.8)),.72);animateAnimal(g,now/1000,2.4,Math.atan2(-(3.5+i*1.8),side*(2.8+i*.45)));});const centipedeSpeed=enemy.state==='chase'?3.9:enemy.state==='patrol'?.84:enemy.state==='warning'?.35:.8;centipede.position.set(enemy.x,-enemy.y,.02);animateCentipede(centipede,now/1000,centipedeSpeed);const gejiPhase=elapsed%10,gejiX=LEFT-3+(gejiPhase-.9)*8;geji.visible=gejiPhase>=.9&&gejiPhase<4.8;geji.position.set(gejiX,-61,.72);wind.visible=gejiPhase<.9;wind.scale.y=1+gejiPhase*12;geji.rotation.z=0;gecko.visible=player.y>68&&player.y<87;gecko.position.set(geckoAttack.x,-geckoAttack.y,.72);gecko.scale.setScalar(geckoWarning>0?1+.12*Math.sin(now*.015):1);gecko.rotation.z=Math.atan2(-(geckoAttack.ty-geckoAttack.y),geckoAttack.tx-geckoAttack.x);slipper.visible=humanTimer>=1.2;slipper.position.x=26+(humanTimer-2.2)*4;camera.position.set(player.x+7,-player.y+5,22);camera.lookAt(player.x,-player.y-2,.3);lamp.position.set(player.x,-player.y+1,4);renderer.render(scene,camera);}
 function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;let speed=0;if(started&&!ended){invulnerable=Math.max(0,invulnerable-dt);lossNotice=Math.max(0,lossNotice-dt);elapsed+=dt;speed=move(dt);if(sheltered()){checkpoint.x=player.x;checkpoint.y=player.y;}updateEnemy(dt);updateHazards(dt,elapsed);const gap=nearGap(),tooNarrow=!!gap&&gap.width<bodySize,danger=enemy.state==='warning'||enemy.state==='chase',gejiWarning=player.y>54&&player.y<68&&(elapsed%10)<.9;const warning=lossNotice>0?'Gが1体、減りました':humanTimer>=0?(humanTimer<1.2?'床板が、上で軋み始めた。':'重い影が、隙間を横切る。'):molting>0?'背中が裂け、白い脚が壁に貼りつく。':!molted&&moltHold>0?'殻の内側が、ゆっくり膨らむ。':tooNarrow?'胸が擦れる。ここはもう通れない。':danger?(enemy.state==='warning'?'粉塵が、下から浮いた。':'ムカデの頭が、こちらへ向いた。'):geckoWarning>0?'巾木の影が、呼吸のように膨らむ。':gejiWarning?'配管の上で、細い脚音が増えていく。':probe&&gap?(gap.width>=bodySize?'触角の先に、身体を隠せる奥行きがある。':'触角が、奥で戻ってきた。'):'';document.querySelector('#warning')!.textContent=warning;document.querySelector('#population')!.textContent=survivors+' 匹';document.querySelector('#objective')!.textContent=player.y<28?'配線と間柱のシャフト':player.y<58?'湿った配管の分岐':player.y<82?'巾木の裏':'キッチンの床下';audio.update(dt,{speed:speed/3.6,danger:danger?1:gejiWarning||geckoWarning>0? .8:humanTimer>=0?.9:0,pan:Math.sign(enemy.x-player.x),molting:molting>0,stamina:1,human:humanTimer>=0?1:0,vertical:enemy.y-player.y,loss:lossNotice>2});}render(now,speed);}
 if(import.meta.env.DEV&&new URLSearchParams(location.search).has('test'))Object.assign(window,{chapter2Test:{step(dt:number){if(ended)return;elapsed+=dt;invulnerable=Math.max(0,invulnerable-dt);move(dt);if(sheltered()){checkpoint.x=player.x;checkpoint.y=player.y;}updateEnemy(dt);updateHazards(dt,elapsed);},setPosition(x:number,y:number){player.x=x;player.y=y;},snapshot(){return{...player,survivors,enemy:{...enemy},elapsed,height:heightAt(player.x,player.y),geckoAttack:{...geckoAttack},sheltered:sheltered(),molted,bodySize,humanTimer,geckoTimer,geckoWarning,moltHold,molting};},setEnemy(state:CentipedeState,y:number,timer=0,x=7){enemy.state=state;enemy.x=x;enemy.y=y;enemy.timer=timer;},startMolt(){molting=3.2;}}});requestAnimationFrame(frame);
}
